name: Docker build and create release

on:
  push:
    branches: [master, main]
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '!README.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build empscripten
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build libopenmpt target wasm
        run: bash -x build.sh
      - name: Build libopenmpt target js
        run: REBUILD=0 TARGET=js bash -x build.sh
      - name: Build libopenmpt target audioworkletprocessor
        run: REBUILD=0 TARGET=audioworkletprocessor bash -x build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            *.js
            *.wasm
            *.mem
          if-no-files-found: error

  create-release:
    name: Get artifacts, create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
      - name: Create release using 'gh'
        run: |
          gh release create libopenmpt-emscripten-all-$(date +%Y%m%d%M) $(find -type f -printf '%p ') --notes-file - <<'#####'
          libopenmpt emscripten
          targets: javascript, wasm and audioworkletprocessor

          [changelog](https://github.com/silv3rr/docker-libopenmpt/blob/main/README.md#changelog)

          #####
        working-directory: ./build-artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
