name: Docker build and create release

on:
  push:
    branches: [master, main]
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '!README.md'
  pull_request:
  workflow_dispatch:

jobs:
  docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull image
        run: docker pull emscripten/emsdk:latest
      - name: Build
        run: bash build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            *.js
            *.wasm
            *.mem
          if-no-files-found: error

  create-release:
    name: Get artifacts, create release
    runs-on: ubuntu-latest
    needs: [docker-image]
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
      - name: Create release using 'gh'
        run: |
          gh release create libopenmpt $(find -type f -printf '%p ') --notes-file - <<'#####'
          libopenmpt empscripten (js)
          
          #####
        working-directory: ./build-artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
